<?php
$module_control_intro = __('These options allow you to control the BASE gPress modules...', 'gpress');
$gtagged_posts_intro = __('These options allow you to fine-tune the geo-tagged post functionality...', 'gpress');
$excerpt_settings_intro = __('This allows you to control the way excerpts are handled on the homepage of your theme. Some themes strip-out HTML tags with the excerpts, or use full-content instead - so these options provide fine-grain control over these components...', 'gpress');
$map_settings_intro = __('These options allow you to control the rendered maps...', 'gpress');
$marker_settings_intro = sprintf(__('<p>These options allow you to upload or link to custom images for markers...</p><p>The markers themselves should be 30px by 30px, whereas the shadows behind them should be 40px by 40px. Both should be transparent PNGs, and if you plan to upload from this page, you will need to ensure the following folder can be accessed (CHMOD 777):</p><p><strong>%s/gpress-admin/fieldtypes/image_upload/uploads/</strong></p>', 'gpress'), GPRESS_URL);
$loop_settings_intro = __('<p>All options from the Advanced Settings tab are only visible to Super Admins.</p><p>These allow you to add or remove the places shown on the homepage by controlling the post types querried. If loops start acting strange, please switch to "POSTS ONLY", which removes the the filters...</p><p>Please note that some plugins are unable to handle post_type arrays, and only work when querrying one type, such as either posts or places...</p>', 'gpress');
$sitewide_intro = __('All other options from the gPress options are based on individual Blog IDs, and allow each blog to set-up their own indepedent options, whereas these Sitewide Options are applied to the entire network and can overwrite the individual settings where selected...', 'gpress');
$brand_settings_intro = __('<p>All options from the Advanced Settings tab are only visible to Super Admins.</p><p>Although it is hugely appreciated if you provide some form of shout-back or recognition for gPress, we understand that some situations require re-branding, and do not want you to edit core files, so please use these options instead:</p>', 'gpress');
$credits_intro = __('<p>All options from the Advanced Settings tab are only visible to Super Admins.</p><p>These options allow you to remove our credits from the front-end...</p><p>Although it is hugely appreciated if you provide some form of shout-back or recognition for gPress, we understand that some situations require re-branding, and do not want you to edit core files, so please use these options instead:</p>', 'gpress');
$misc_intro = __('Other MISC advanced settings can be found here, such as the removal of jQuery from your theme, emergency deactivation of Foursquare, and so forth...', 'gpress');
$foursquare_intro = __('These options allow you to integrate with Foursquare...', 'gpress');
$bpcomp_intro = __('These options allow you to control the BuddyPress integration...', 'gpress');
$lang_ling_intro = __('<p>If you have defined WPLANG and the "gpress-lang" folder contains the relevant .mo file, gPress will automatically switch languages. In the future, these options will allow you to also control lingo by changing the references of certain things, but have found with so many changes to the core with each new version, it is hard to maintain two or more languages (which is what LINGO essentially is), so for now, the only way to change the language / lingo manually is by typing the name of the file below...</p><p><strong>HOWEVER</strong>, please note that after switching language and clicking "SAVE CHANGES", you will need to refresh the page once again to ensure everything gets flushed and refreshed properly...</p>', 'gpress');
$bp_styling_intro = __('These options allow you to style certain BuddyPress components...', 'gpress');
?>